[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django_reference_implemetation"
authors = [{name = "SimpleCTO", email = "github+django_reference_implementation@simplecto.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dscription = "Django Reference Implementation, a boilerplate Django project."
versions = "0.1.0"

[project.urls]
Home = "https://github.com/simplecto/django-reference-implementation"

[tool.ruff]
# Set the maximum line length to 120.
line-length = 120
target-version = "py312"
exclude = [
    "pyproject.toml",
    "src/**/tests/*",
    "src/**/migrations/*",
    ".idea/**",
    "src/manage.py",
]

[tool.ruff.lint]

ignore = [
    "ANN101",
    "E501",
    "D203",
    "D213",
    "D100",
    "COM812",
    "RUF012",
]
select = ["ALL", "W2", "I"]
exclude = [
    "pyproject.toml",
    "src/**/tests/**",
    "src/**/migrations/**",
    ".idea/**",
    "src/manage.py",
]

[tool.bandit]
exclude = ["src/**/tests/**", "src/**/migrations/*"]
skips = ["B106"]
