[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django_reference_implemetation"
authors = [{name = "SimpleCTO", email = "github+django_reference_implementation@simplecto.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dscription = "Django Reference Implementation, a boilerplate Django project."
version = "0.1.0"

[project.urls]
Home = "https://github.com/simplecto/django-reference-implementation"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
    "pyproject.toml",
    "src/**/tests/*",
    "src/**/migrations/*",
    ".idea/**",
    "src/manage.py",
]

[tool.ruff.lint]

ignore = [
    "ANN101",
    "E501",
    "D203",
    "D213",
    "D100",
    "COM812",
    "RUF012",
]
select = ["ALL", "W2", "I"]
exclude = [
    "pyproject.toml",
    "src/**/tests/**",
    "src/**/migrations/**",
    ".idea",
    "src/manage.py",
]

[tool.bandit]
exclude = ["src/**/tests/**", "src/**/migrations/*"]
skips = ["B106"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "$version"
bump_message = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
version_files = [
    "pyproject.toml:^version",
    "Dockerfile:VERSION",
]

[tool.pyright]
include = ["src"]
typeCheckingMode = "basic"
exclude = [
    "**/tests",
    "**/migrations",
    "**/__pycache__",
    "**/node_modules",
    ".git",
]

# Django-specific settings
reportMissingImports = true
reportGeneralTypeIssues = "warning"
reportMissingTypeStubs = false
reportUnknownMemberType = "warning"
reportUnknownParameterType = "warning"
reportUnknownVariableType = "warning"
reportUntypedFunctionDecorator = "warning"
reportOptionalSubscript = true
reportOptionalMemberAccess = true
reportOptionalCall = true

# Important for Django
reportUnknownArgumentType = "warning"
reportUnusedImport = "warning"
reportDuplicateImport = "error"

pythonVersion = "3.12"
pythonPlatform = "Linux"

# Virtual environment settings
venvPath = "."
venv = ".venv"

# Django-specific type checking settings
stubPath = "typings"


# Additional Django settings
extraPaths = ["src"]

[tool.django-stubs]
django_settings_module = "config.settings"  # Adjust this to your settings module path
strict_settings = true
