name: Django Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t dri-test .

    - name: Run Django tests
      run: |
        docker run --rm \
          -v $(pwd)/env.test:/env \
          dri-test \
          python manage.py test
